### ISSUE TITLE
Magic Script

### ISSUE THREAD

**Issue by kellensinclair** [joemcbride/outlander-osx-scripts#4]
When trying to use the magic script, I put in .magic seer 20 25 Agumentation maxexp.

All that happens is script puts in prep seer 20 constantly, then casts, then repeats

**Comment by joemcbride** [comment]
Did you add your spell preparation text to the list?  Line 7 of the script.  That is my first guess.

https://github.com/joemcbride/outlander-osx-scripts/blob/master/magic.cmd#L7

These are the ones that the script currently knows about:

```
var spellPrep With tense movements you|You begin chanting|With rigid movements
```

**Comment by joemcbride** [comment]
It also expects you have a `camb_item` global variable that is your cambrinth item.

Can type this at the command prompt to set it:

```
#var camb_item armband
```

**Comment by kellensinclair** [comment]
That was it!

I thought spellprep meant the spell i was using, not what it says when i am prepping the spell..

oops
